version: '3'

services:
  # HACKY WAY TO GET VOLUME WORKING
  # DON'T DO IT IN PRODUCTION
  init-data:
    image: busybox
    command: chmod -R 777 /data
    volumes:
      - surrealdb-data:/data

  surrealdb:
    image: surrealdb/surrealdb:latest
    entrypoint:
      - /surreal
      - start
      - --user
      - backend
      - --pass
      - password
      - --log
      - debug
      - rocksdb://data
    ports:
      - "8100:8000"
    networks:
      - mapper-influences-rs 
    volumes:
      - surrealdb-data:/data
    depends_on:
      init-data:
        condition: service_completed_successfully

  mapper_influences_backend:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - surrealdb
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 5
    ports:
      - "${PORT}:${PORT}"
    networks:
      - mapper-influences-rs 
    environment:
      SURREAL_USER: backend
      SURREAL_PASS: ${SURREAL_PASS:-password} 
      SURREAL_URL: ${SURREAL_URL:-ws://surrealdb:8000} # Docker internal port 
      REDIRECT_URI: http://localhost:8000/oauth/osu-redirect
      POST_LOGIN_REDIRECT_URI: http://localhost:3000/dashboard
      JWT_SECRET_KEY: localkey
      ADMIN_PASSWORD: localpass
      PORT: 8000
      CLIENT_ID: $CLIENT_ID
      CLIENT_SECRET: $CLIENT_SECRET

networks:
  mapper-influences-rs:

volumes:
  surrealdb-data:
