version: '3'

services:
  surrealdb:
    env_file:
      - .env
    entrypoint: 
      - /surreal 
      - start 
      - --user
      - $SURREAL_USER
      - --pass
      - $SURREAL_PASS
      - --log
      - debug 
    image: surrealdb/surrealdb:latest
    ports:
      - 8100:8000

